### ISSUE TITLE
Internal/ring gears?

### ISSUE THREAD

**Issue by pperrin** [looooo/freecad.gears#6]
Not sure this is the place to put questions, but...

Is it possible to generate internal ring gears for planetary gear systems?

I can generated them with other software, and if the maths is right they should work(!) - but it would be neat to do it all in the place.

**Comment by looooo** [comment]
it's possible, to do them with part-wb. (Make a ring and subtract an inner gear) The problem is that the gears have no parameter for the height of the head....
![planetary](https://cloud.githubusercontent.com/assets/5084704/22501839/cf2fe1ac-e86a-11e6-91d0-5bcab1d53202.png)
But you can also use functionality of part-design: change to part-design-wb:In top menu choose Part-Design and select the Involute Gear at the bottom. There you have the option to choose an inner or outer profile.

**Comment by pperrin** [comment]
Thanks for the suggestions - I understand the inner ring teeth are a different profile so the 'subtraction' method doesn't work well.

The built in gears come out just too big when 3d printed and don't have any parameters to adjust to give them a bit more tollerance... but I'll try the built in ring gears and see if your workbench has enough parameters to do all the adjusting on the star/planets...

Thanks

**Comment by looooo** [comment]
I have added 2 new properties to the involute gear. With these you can manipulate the tooth-hight and also make the tooth thicker (reversed backlash). With this it's possible to create inner gears...

![tolerance](https://cloud.githubusercontent.com/assets/5084704/22592288/4acdc888-ea19-11e6-9138-47d6d6b8ea96.png)
![par1](https://cloud.githubusercontent.com/assets/5084704/22592289/4ca872ac-ea19-11e6-8b72-54d978dc1c79.png)

**Comment by pperrin** [comment]
Cool - I have installed the new files - I don't know when I'll be back on gears, but when I am I'll let you know how it goes.

Great Job - thanks.

**Comment by alexisdal** [comment]
hello,
First of all, thanks for this excellent piece of software directly integrated in freecad. very convenient indeed. 

i'm trying to use it to design some planetary gears as well but i'm also facing the same issue with the ring/annulus.

It seems the new parameters (reverse backlash and head) should do the trick.

However, i am somehow suprised by the value of bashslash. for a 12-36-96 planetary gears (in teeth count for sun, planet and ring espectively). the -- apparently correct -- value i found are
0.1mm of head 
0.006m reverse bashlash

head value fees ok.
however, bashlslash feels very very tiny. is it normal ?

**Comment by looooo** [comment]
>0.006m reverse bashlash
Maybe you  meant 0.006 mm?
I think the head-parameter is multiplied with the module. As I thought backlash is more related to machine-tolerance and not dependent on the module (diameter) it's given by an absolute-value. If there is any good documentation (or standardization) regarding these parameters I can update the geometry-influence of these parameters.

**Comment by kcleung** [comment]
A spline on a CV shaft is a good example of a tooth axle:

https://en.wikipedia.org/wiki/Spline_(mechanical)

**Comment by kcleung** [comment]
And when we make an internal gear, the gear may well also have an external gear too.

**Comment by sdfgeoff** [comment]
It is worth noting that the solution above (adjusting backlash etc.) works for when the interior/exterior gears differ only slightly in tooth count, it does not work well when the tooth counts differ significantly.

In the end I decided to go with cylindrical gears, so I could use the built in involute gear tool.

**Comment by looooo** [comment]
> It is worth noting that the solution above (adjusting backlash etc.) works for when the interior/exterior gears differ only slightly in tooth count, it does not work well when the tooth counts differ significantly.
> 
> In the end I decided to go with cylindrical gears, so I could use the built in involute gear tool.

Can you explain? maybe add some Images to visualize the issue.

**Comment by sdfgeoff** [comment]
Disclaimer: I'm no expert on gears. If someone more knowledgable says otherwise, go with them.

Here is a 24 ring gear and a six tooth pinion  (yeah, I know you shouldn't make them that tiny) I've already got a bit of negative backlash in here, but would need a fair bit more to give adequate clearance.
![gearmesh](https://user-images.githubusercontent.com/13490050/103517940-cda4d900-4ed7-11eb-87af-24917197f20e.png)

Here's a 9 tooth pinion to a 24 tooth ring gear:
![9x24_default](https://user-images.githubusercontent.com/13490050/103518696-1c06a780-4ed9-11eb-9a01-21165d80b48c.png)

There's no backlash/head in the model in this demo, and you can see that I'd need to adjust the amount of compensation to be about half the width of the "tooth" on the ring gear (green) which would result on the loading being on the tooth "flank" (yellow  arrow)
If the tooth profile was flipped (cyan) then the loading would be on the tooth flank (I think).

Possible useful reference (I'll have a more detailed look at this tomorrow, but at the very least it seems to hint that there is a difference): https://gearsolutions.com/departments/tooth-tips/internal-ring-gears-design-and-considerations/

**Comment by looooo** [comment]
Does a bottom-fillet-radius property solve this issue? This is on the list for a long time.

**Comment by looooo** [comment]
Btw. Try to set the clearance property of the inner gear to a negative number to cut the intersecting part. Or use a Tube-Feature of the Part-Workbench to increase the inner radius.

![Uploading Bildschirmfoto von 2021-01-05 15-29-00.png…]()

**Comment by sdfgeoff** [comment]
Hmm, I didn't try the clearance option. That does indeed seem like it would fix it. An bottom fillet option may be nice, but with the clearance parameter, I'm not sure if it's needed.

**Comment by jrmoserbaltimore** [comment]
Is it difficult to implement a property that just turns an involute or cycloid gear into a ring gear?  (In the scale that implementing anything like this is difficult)

**Comment by looooo** [comment]
@jrmoserbaltimore if there are special properties necessary for the internal-gear I think it's best to create a new feature. For now please use a workaround with boolean operation eg. Part-workbench

**Comment by jrmoserbaltimore** [comment]
Thanks.  I wasn't sure if this had been decided the appropriate approach or if it's just a for-the-future thing.

I guess generating an entire planetary gear set at once would make some sense, but be hard, and take a while to implement.

**Comment by looooo** [comment]
Btw. with the addition of fillets I don't see any issues with creating internal gear rings.
